# Generated by Django 5.1.3 on 2024-11-09 02:42

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.FileField(upload_to='application', validators=[catalog.models.validate_image], verbose_name='Загрузите фото заявки'),
        ),
    ]
