# Generated by Django 5.1.3 on 2024-11-08 03:40

import catalog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Выберите название категории', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Напишите заголовок к заявке', max_length=200)),
                ('description', models.TextField(help_text='Напишите к заявке описание')),
                ('image', models.ImageField(help_text='Загрузите фото заявки', upload_to='application', validators=[catalog.models.validate_image])),
                ('status', models.CharField(choices=[('n', 'Новая'), ('a', 'Принято в работу'), ('s', 'Выполнено')], default='n', help_text='Статус заявки', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Дата и время создания заявки')),
                ('category', models.ForeignKey(help_text='Выберите категорию заявки', on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
            ],
        ),
    ]
