# Generated by Django 5.1.3 on 2024-11-08 06:44

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_category_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.category', verbose_name='Выберите категорию заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(verbose_name='Напишите к заявке описание'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(upload_to='application', validators=[catalog.models.validate_image], verbose_name='Загрузите фото заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('n', 'Новая'), ('a', 'Принято в работу'), ('s', 'Выполнено')], default='n', help_text='Статус заявки', max_length=1, verbose_name='Статус заявки'),
        ),
        migrations.AlterField(
            model_name='application',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Напишите заголовок к заявке'),
        ),
    ]
